/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;

import java.util.Date;

/**
 *
 * @author ragrag
 */
public class customerScreen extends javax.swing.JFrame {

    /**
     * Creates new form customerScreen
     */
   Pharmacy p;
    Admin admin;
    Customer customer;

    public customerScreen(Pharmacy p,Admin admin,Customer customer) {
        this.p = p;
        this.admin =admin;
        this.customer = customer;
       
        initComponents();
  
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mkBtn = new javax.swing.JButton();
        viBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Customer");

        mkBtn.setText("Make Order");
        mkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mkBtnActionPerformed(evt);
            }
        });

        viBtn.setText("View Orders");
        viBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viBtn)
                            .addComponent(mkBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(backBtn)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(mkBtn)
                .addGap(18, 18, 18)
                .addComponent(viBtn)
                .addGap(55, 55, 55)
                .addComponent(backBtn)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
 java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainScreen(p,admin,customer);
            }
        });
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void mkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mkBtnActionPerformed
 java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerMakeOrder(p,admin,customer);
            }
        });
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_mkBtnActionPerformed

    private void viBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viBtnActionPerformed
 java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerViewOrders(p,admin,customer);
            }
        });
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_viBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mkBtn;
    private javax.swing.JButton viBtn;
    // End of variables declaration//GEN-END:variables
}
